export default {
    SET_LOCAL: '@local/SET_LOCAL',

    DATA_IN_REQUEST: '@local/DATA_IN_REQUEST',
    DATA_IN_SUCCESS: '@local/DATA_IN_SUCCESS',
    DATA_IN_FAILURE: '@local/DATA_IN_FAILURE',

    STORE_IN_REQUEST: '@local/STORE_IN_REQUEST',
    STORE_IN_SUCCESS: '@local/STORE_IN_SUCCESS',
    STORE_IN_FAILURE: '@local/STORE_IN_FAILURE',

    UPDATE_IN_REQUEST: '@local/UPDATE_IN_REQUEST',
    UPDATE_IN_SUCCESS: '@local/UPDATE_IN_SUCCESS',
    UPDATE_IN_FAILURE: '@local/UPDATE_IN_FAILURE',

    DESTROY_IN_REQUEST: '@local/DESTROY_IN_REQUEST',
    DESTROY_IN_SUCCESS: '@local/DESTROY_IN_SUCCESS',
    DESTROY_IN_FAILURE: '@local/DESTROY_IN_FAILURE',
};
